FIX React components for reactstrap 8 upgrade
silverstripe/silverstripe-admin pull request #1128
Opened 2020-10-01 03:10 UTC by emteknetnz

Fixes for https://github.com/silverstripe/silverstripe-admin/issues/1126

2020-10-05 21:02 UTC, Cheddam requested changes
Good to get some basic coverage in place on these components. Some incorrect names, and a couple of places I think we could be a _little_ more specific about the output (I'm aware that these are 'MVP' tests, but we're unlikely to touch them again anytime soon.)

2020-10-05 21:29 UTC, emteknetnz commented on client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
> +      <Input plaintext {...this.getInputProps()} tag="p">{this.props.value}</Input>
I've added an additional case to the storybook that includes an HTML value, it'll render like this

![image](https://user-images.githubusercontent.com/4809037/95134131-d2fe6480-07be-11eb-9db2-808cb9412135.png)

2020-10-05 21:34 UTC, emteknetnz commented on client/src/components/ResizeAware/tests/ResizeAware-test.js
> +      expect(reactWrapper.find('div')).toHaveLength(1);
Note really https://github.com/silverstripe/silverstripe-admin/blob/1/client/src/components/ResizeAware/ResizeAware.js

2020-10-05 21:51 UTC, emteknetnz commented on client/src/components/Toolbar/tests/Toolbar-test.js
> +      expect(reactWrapper.find('div.toolbar')).toHaveLength(1);
Couldn't find a reliable way to do this, so I removed the back button unit test and created an MVP story book that includes a back button 'test'

![image](https://user-images.githubusercontent.com/4809037/95136006-d6dfb600-07c1-11eb-9511-aa4cd3c8f9bc.png)

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/MobileMenuToggle/tests/MobileMenuToggle-test.js
> +      expect(reactWrapper.find('button')).toHaveLength(1);
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/SingleSelectField/tests/SingleSelectField-test.js
> +describe('HiddenField', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/Focusedzone/tests/Focusedzone-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/HtmlEditorField/tests/HtmlEditorField-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/Preview/tests/Preview-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/NotFoundComponent/tests/NotFoundComponent-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/MobileMenuToggle/tests/MobileMenuToggle-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/LiteralField/tests/LiteralField-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 21:56 UTC, emteknetnz commented on client/src/components/LabelField/tests/LabelField-test.js
> +describe('FieldGroup', () => {
Updated

2020-10-05 22:24 UTC, Cheddam commented on client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
> +      <Input plaintext {...this.getInputProps()} tag="p">{this.props.value}</Input>
That confirms this is a breaking change. Was `dangerouslySetInnerHTML={this.getContent()}` not working? You might need to nest it in a child element if so.

2020-10-05 23:17 UTC, emteknetnz commented on client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
> +      <Input plaintext {...this.getInputProps()} tag="p">{this.props.value}</Input>
>> dangerouslySetInnerHTML={this.getContent()} not working? 

Yeah there was a big red error thrown

Screenshot above refers to this newly added story:

https://github.com/silverstripe/silverstripe-admin/pull/1128/files#diff-13544a97c2d6bb8894bbff043a685e98R6

I believe this is how it's supposed to work?

2020-10-05 23:57 UTC, Cheddam commented on client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
> +      <Input plaintext {...this.getInputProps()} tag="p">{this.props.value}</Input>
That's not how it worked before, though - this change would be similar to escaping HTML in field descriptions. If this is no longer directly supported by the `Input` component, I recommend taking the approach I suggested of nesting the content in a child element, e.g.

```suggestion
      <Input plaintext {...this.getInputProps()} tag="p"><div dangerouslySetInnerHTML={this.getContent()} /></Input>
```

2020-10-06 01:06 UTC, emteknetnz commented on client/src/components/HtmlReadonlyField/HtmlReadonlyField.js
> +      <Input plaintext {...this.getInputProps()} tag="p">{this.props.value}</Input>
Have reverted behaviour. `dangerouslySetInnerHTML` with reactstrap8 as long as `tag="p"` is present

2020-10-06 02:39 UTC, Cheddam approved these changes

2020-10-06 02:40 UTC, merged