Rescue Master Branch PR: ENH Remove legacy translation behaviour in template
silverstripe/silverstripe-admin pull request #1346
Opened 2022-08-25 04:46 UTC by GuySartorelli

Rescues (and expands upon) https://github.com/silverstripe/silverstripe-admin/pull/78

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10350

2022-08-29 06:23 UTC, emteknetnz requested changes
This looks very different from the rescued commit?

2022-08-29 21:10 UTC, GuySartorelli commented
This PR rescues "and expands upon" the original PR.
I cherry-picked in the commit from the original PR and then looked for instances of what the original commit was doing which had been either missed or added since the original commit was created. The PR would be incomplete if these additional items were left unchanged, since the purpose is to update the old hardcoded string syntax.

2022-08-29 21:15 UTC, GuySartorelli commented
Conflicts resolved.

2022-08-31 21:35 UTC, emteknetnz approved these changes

2022-08-31 21:36 UTC, merged