ENH Records can be made previewable with an extension
silverstripe/silverstripe-admin pull request #1363
Opened 2022-09-14 01:39 UTC by GuySartorelli

## Parent issue
- https://github.com/silverstripe/silverstripe-admin/issues/1362

2022-10-06 02:34 UTC, sabina-talipova commented
@GuySartorelli , could you rebase this against branch `2`, please.

2022-10-06 02:46 UTC, GuySartorelli commented
Rebased on `2`

2022-10-07 01:44 UTC, sabina-talipova requested changes

2022-10-07 01:44 UTC, sabina-talipova commented on code/LeftAndMain.php
>          $page = $this->currentPage();
```suggestion
        $page = $this->currentPage();
        
         if (!$page) {
            return null;
        }
```

2022-10-07 01:45 UTC, sabina-talipova commented on code/LeftAndMain.php
>          $page = $this->currentPage();
All works good! Just small changes, since it breaks Settings section.

2022-10-07 02:21 UTC, GuySartorelli commented on code/LeftAndMain.php
>          $page = $this->currentPage();
I've gone one further - `SiteConfig` should be previewable too! See https://github.com/silverstripe/silverstripe-siteconfig/pull/127 which will need to be merged for CI here to go green.

2022-10-09 19:11 UTC, sabina-talipova approved these changes

2022-10-09 19:11 UTC, merged