DEP Update jquery-ui in thirdparty folder
silverstripe/silverstripe-admin pull request #1424
Opened 2022-12-22 01:37 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1423

jquery-ui v1.9.2  -> v1.13.2

This should have been upgraded as part of 1.12, and since there's an existing regression I think we should do a patch release in 1.12 rather than waiting for 1.13

Updated because of this answer https://stackoverflow.com/a/37925405 - javascript error matched what console error I saw after running `yarn dev` and replicating issue

Issue could be replicated by 
- Creating a test member in the security section of the cms
- Editing a group in the group section of the security section and attempting to add the new member to the group using the autocompleter

2023-01-09 03:31 UTC, emteknetnz commented on client/src/legacy/LeftAndMain.js
> +        selectedTabs.push({id:id, selected:$(el).tabs('option', 'active')});
'selected' was renamed to 'active' - https://bugs.jqueryui.com/ticket/7135

2023-01-09 03:31 UTC, emteknetnz commented on client/src/legacy/LeftAndMain.js
> +        if(!$(el).data('uiTabs')) return; // don't act on uninit'ed controls
'tabs' was renamed to 'uiTabs' in jquery-ui 1.10 - I couldn't find a reference of where this was done, though console.log'ing `$el.data()` showed it to now be `'uiTabs'`

2023-01-09 03:32 UTC, emteknetnz commented on client/src/styles/legacy/_uitheme.scss
> +    color: $link-color;
These CSS changes are effectively to revert some CSS additions that went into later versions of jquery-ui

2023-01-10 00:18 UTC, GuySartorelli commented
@emteknetnz In the installer CI run you linked to, _everything_ is failing... does that link need to be updated to a more recent run? Or does this PR legitimately break everything?

2023-01-10 00:39 UTC, GuySartorelli requested changes
The cursor should be `pointer` when hovering over tabs.

The icon alignment (super minor so not too fussed) and text colour of expandable composite fields is not correct.
**before:**
![image](https://user-images.githubusercontent.com/36352093/211435311-ebabd08b-6029-4af6-adfe-9abfd8cd59fe.png)
**this PR:**
![image](https://user-images.githubusercontent.com/36352093/211435373-844535a2-3529-43a3-930b-fb25fb4a0f60.png)

The arrow icon on expandable composite fields disappears when expanding the field - it should not.

Everything else looks fine - and the reported regression is resolved.

2023-01-10 01:14 UTC, emteknetnz commented
@GuySartorelli updated

2023-01-10 01:22 UTC, GuySartorelli commented
@emteknetnz Can you please respond to my question about the installer CI run?

2023-01-12 04:07 UTC, GuySartorelli approved these changes
Looks good, works great locally.

2023-01-12 04:08 UTC, merged

2023-01-12 04:10 UTC, GuySartorelli commented
Released as [1.12.1](https://github.com/silverstripe/silverstripe-admin/releases/tag/1.12.1)