FIX Set the value correctly when passed as prop.
silverstripe/silverstripe-admin pull request #1432
Opened 2023-01-09 00:04 UTC by GuySartorelli

Fixes part of https://github.com/silverstripe/silverstripe-cms/actions/runs/3726652553/jobs/6320241058

After `".Select-multi-value-wrapper" element not found` is resolved by a combination of https://github.com/silverstripe/silverstripe-cms/pull/2811 and https://github.com/silverstripe/silverstripe-framework/pull/10635, we get `The text "About Us" was not found in the text of the element matching css ".treedropdownfield__value-container".`

This PR addresses that by ensuring we _do_ set a value if we have a value and it's available in the options.

## Parent issue
- https://github.com/silverstripeltd/product-issues/issues/655

2023-01-10 23:20 UTC, maxime-rainville requested changes
TreeDropdownField.js is used to render the regular TreeDropdown outside of React views.

This means it can be rendered outside the context of `<App />`.

Your PR seems to be breaking this.

**With the PR**
![Screenshot from 2023-01-11 12-15-36](https://user-images.githubusercontent.com/1168676/211682416-2406525c-c55d-4586-b1e7-2327437822c0.png)

**Without PR**
![image](https://user-images.githubusercontent.com/1168676/211682567-241d3948-bc34-4b79-8c8a-1f58fd4d90bf.png)

2023-01-10 23:20 UTC, maxime-rainville commented on client/src/containers/EmotionCssCacheProvider/EmotionCssCacheProvider.js
> +function EmotionCssCacheProvider({ children }) {
My instinct would have been to write this as an HOC. But it's also fine the way it is.

2023-01-10 23:28 UTC, GuySartorelli commented
> TreeDropdownField.js is used to render the regular TreeDropdown outside of React views.
> This means it can be rendered outside the context of <App />.
> Your PR seems to be breaking this.

Shoot, good point... that means we're going to have to expose the new cache component (so `silverstripe/cms` at least can use it), which means a new alpha release of `@silverstripe/webpack-config` - but we needed to do that eventually anyway to expose apolloclient so I'll do that at the same time.

2023-01-11 02:07 UTC, GuySartorelli commented
@maxime-rainville I've resolved the issue with this one. There's also now a corresponding PR for webpack-config.
Both of these will need to be merged before I can update the cms PR to use the new component.

2023-01-11 04:13 UTC, maxime-rainville approved these changes
Tested locally and it works great.

2023-01-11 04:14 UTC, merged