FIX: Don't show success HTTP status messages as popups (fixes #1428)
silverstripe/silverstripe-admin pull request #1444
Opened 2023-01-18 16:59 UTC by kinglozzer

2023-01-20 00:35 UTC, michalkleiner commented on client/src/legacy/LeftAndMain.js
> +    if (!msg && (xhr.status < 200 || xhr.status > 399)) {
```suggestion
    if (!msg && msgType === 'error') {
```
or
```suggestion
    if (!msg && msgType !== 'success') {
```

2023-01-23 13:00 UTC, kinglozzer commented
I’ve rebuilt the JS and squashed

2023-01-24 03:08 UTC, michalkleiner approved these changes

2023-02-14 03:51 UTC, GuySartorelli requested changes
With this solution, batch actions success toasts are no longer displayed - which probably means we're doing those the wrong way and they probably don't display in http 2.
https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText
> Note that HTTP/2 does not support status messages. 

I think to get this merged we'll need to find everywhere that sets status text with the intention of setting toast messages and use the header instead.
We also can't do this in a patch release - arguably we can't do it in a minor either because it'll break for someone.

2023-02-14 03:52 UTC, GuySartorelli commented
Maybe the solution for CMS 4 is to make `ignoredMessages` configurable (somehow), and for CMS 5 we can make the change this PR proposes.

2023-02-14 09:58 UTC, kinglozzer commented
>With this solution, batch actions success toasts are no longer displayed - which probably means we're doing those the wrong way and they probably don't display in http 2.

I think that’s a separate issue as batch actions have their own separate code for this: https://github.com/silverstripe/silverstripe-admin/blob/7a2de3e8f1f9166c27b0f3abd0a21e8b736f8df5/client/src/legacy/LeftAndMain.BatchActions.js#L285-L304

I did quickly test setting `X-Status` for batch actions, but it doesn’t work because the `statusMessage()` function (called line 303) isn’t globally available, so it just causes an error:

> Uncaught ReferenceError: statusMessage is not defined

We could probably treat these as two separate issues

2023-02-14 20:10 UTC, GuySartorelli commented
The fact is that this PR breaks those toast messages - so if we don't change the way those are output, this is definitely a breaking change.

2023-02-15 09:10 UTC, kinglozzer commented
> The fact is that this PR breaks those toast messages - so if we don't change the way those are output, this is definitely a breaking change.

Ah sorry, I was testing _without_ this PR applied but I was testing on HTTP2 - your assertion above is correct, batch action messages are already broken in HTTP2 environments. So this would potentially be a breaking change in HTTP1 environments

Should I target this PR to `2.0`? We could then re-open https://github.com/silverstripe/silverstripe-admin/pull/1429 as the fix for the `1.x` release line

2023-02-15 20:57 UTC, GuySartorelli commented
Yeah I think that's a good idea.
This PR probably shouldn't be merged into `5.0` without those toasts being changed though. Even though it's kind of a separate issue, this PR would still represent a regression without those toasts using the correct API for toast generation.

2023-12-19 01:49 UTC, GuySartorelli commented
The window for this being included in Silverstripe CMS 5 as a breaking change has long passed. As discussed above it would be a breaking change for HTTP/1 environments, which is basically anyone running apache without php-fpm.

I'm going to close this for now - @kinglozzer if you still think this is a valuable change, we'll be starting CMS 6 work in the new year, so we'll be making CMS 6 branches for this sort of thing at that time.

2023-12-19 01:49 UTC, closed without merging