MNT Use React Testing Library
silverstripe/silverstripe-admin pull request #1497
Opened 2023-04-11 22:42 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1419

2023-05-03 02:46 UTC, emteknetnz commented on client/src/components/TreeDropdownField/tests/TreeDropdownField-test.js
> -  describe('lazyLoad()', () => {
Even after spending several hours on this, I was simply unable to get lazyLoad() to trigger

2023-05-03 03:05 UTC, emteknetnz commented on client/src/components/TreeDropdownField/tests/TreeDropdownField-test.js
> -  describe('handleKeyDown()', () => {
These were all testing whether a class method was called, rather than testing if a callback passed as a callback was called

2023-05-03 03:22 UTC, emteknetnz commented on client/src/components/TreeDropdownField/tests/TreeDropdownField-test.js
> -  describe('getDropdownOptions()', () => {
These were all testing the output of a class method that was passed as a prop to a react-select component

2023-05-03 03:25 UTC, emteknetnz commented on client/src/components/TreeDropdownField/tests/TreeDropdownField-test.js
> -    it('should return a breadcrumb path separated by /', () => {
This test is now covered by `TreeDropdownField getBreadcrumb() should traverse the path given and return the relevant nodes in the tree`

2023-05-03 04:01 UTC, emteknetnz commented on client/src/components/PopoverOptionSet/tests/PopoverOptionSet-test.js
> -    it('render all buttons matching the search term', () => {
These two tests would rely on logic passed in from the onSearch callback i.e. these tests wouldn't be testing anything within the actual code

2023-05-03 04:20 UTC, emteknetnz commented on client/src/containers/InsertLinkModal/tests/InsertLinkModal-test.js
> -/* global jest, describe, it, expect, beforeEach */
This component doesn't render at all when using RTL

2023-05-03 05:20 UTC, emteknetnz commented on client/src/components/Breadcrumb/tests/breadcrumb-test.js
> -/* global jest, describe, beforeEach, it, expect */
Changed the casing of the filename to 'Breadcrumb-test.js'

2023-05-09 03:51 UTC, sabina-talipova requested changes
Just small comment from https://testing-library.com/docs/react-testing-library/api/#container-1
>  If you find yourself using container to query for rendered elements then you should reconsider! The other queries are designed to be more resilient to changes that will be made to the component you're testing. Avoid using container to query for elements!

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/Badge/tests/Badge-test.js
> +  expect(container.querySelectorAll('.badge').length).toBe(0);
```suggestion
  expect(container.querySelector('.badge')).toBeNull();
```

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/Breadcrumb/tests/Breadcrumb-test.js
> +  const links = container.querySelectorAll('.breadcrumb__item-title');
```suggestion
  const links = container.querySelectorAll('.breadcrumb__item-title');
  expect(links).toHaveLength(3);
```

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/CompositeField/tests/CompositeField-test.js
Why did you remove test cases that are related to `tag` and `legend`?

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/FieldHolder/tests/FieldHolder-test.js
> +test('FieldHolder titleTip', () => {
```suggestion
test('FieldHolder titleTip should be rendered if one is provided', () => {
```

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/FieldHolder/tests/FieldHolder-test.js
> +test('FieldHolder titleTip', () => {
```suggestion
test('FieldHolder titleTip should not be rendered if one is not provided', () => {
```

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/Form/tests/Form-test.js
Could we return back test for `adds an invalid class when valid is false`?

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/Form/tests/Form-test.js
> +  expect(messages).toHaveLength(2);
```suggestion
  expect(messages).toHaveLength(2);
  expect(messages[0].props.className).toContain('message-box--panel-top');
   expect(messages[1].props.className).not.toContain('message-box--panel-top');
```

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/TextField/tests/TextField-test.js
> +  expect(container.querySelectorAll('textarea')).toHaveLength(1);
Could we check that textarea has 3 lines?

2023-05-09 03:51 UTC, sabina-talipova commented on client/src/components/TextField/tests/TextField-test.js
> +  expect(container.querySelector('input').getAttribute('type')).toBe('text');
Could we check that `multiLine() should not be multi-line for empty data`?

2023-05-09 22:10 UTC, emteknetnz commented
> If you find yourself using container to query for rendered elements then you should reconsider!

We're way too far through this progress to move away from container based querying at this point since that's what the majority of the refactored tests use

2023-05-09 22:11 UTC, emteknetnz commented on client/src/components/Badge/tests/Badge-test.js
> +  expect(container.querySelectorAll('.badge').length).toBe(0);
Updated

2023-05-09 22:11 UTC, emteknetnz commented on client/src/components/Breadcrumb/tests/Breadcrumb-test.js
> +  const links = container.querySelectorAll('.breadcrumb__item-title');
Updated

2023-05-09 22:20 UTC, emteknetnz commented on client/src/components/CompositeField/tests/CompositeField-test.js
Added

2023-05-09 22:21 UTC, emteknetnz commented on client/src/components/FieldHolder/tests/FieldHolder-test.js
> +test('FieldHolder titleTip', () => {
Updated

2023-05-09 22:21 UTC, emteknetnz commented on client/src/components/FieldHolder/tests/FieldHolder-test.js
> +test('FieldHolder titleTip', () => {
Updated

2023-05-09 22:34 UTC, emteknetnz commented on client/src/components/Form/tests/Form-test.js
This whole file wasn't converted, I've updated it to use react-testing-library

2023-05-09 22:34 UTC, emteknetnz commented on client/src/components/Form/tests/Form-test.js
> +  expect(messages).toHaveLength(2);
I've rewritten the whole file

2023-05-09 22:40 UTC, emteknetnz commented on client/src/components/TextField/tests/TextField-test.js
> +  expect(container.querySelector('input').getAttribute('type')).toBe('text');
We do by checking that it's input tag instead of a textarea tag. The multiline test below checks for a textarea tag

2023-05-09 22:41 UTC, emteknetnz commented on client/src/components/TextField/tests/TextField-test.js
> +  expect(container.querySelectorAll('textarea')).toHaveLength(1);
Updated

2023-05-10 00:52 UTC, sabina-talipova approved these changes
Nice work! Looks good to me 👍

2023-05-10 00:53 UTC, merged