ENH Behat test Gridfield pagination after search
silverstripe/silverstripe-admin pull request #1528
Opened 2023-06-19 22:02 UTC by sabina-talipova

## Description
Added a new test case to test that the Gridfield keeps pagination (when needed) after search.
## Parent issue
- https://github.com/symbiote/silverstripe-queuedjobs/issues/405

2023-06-20 00:41 UTC, sabina-talipova commented
Failed tests require the PR https://github.com/silverstripe/silverstripe-framework/pull/10825 to be merge.

2023-06-21 00:03 UTC, emteknetnz requested changes
Please change the commit message and pull-request title prefix from 'ENH' to 'MNT'

2023-06-21 02:42 UTC, emteknetnz requested changes
Sorry - as mentioned on https://github.com/silverstripe/silverstripe-framework/pull/10825#pullrequestreview-1489534976 - could you please rebase / retarget to 2.0 since it's a bugfix

2023-06-21 04:35 UTC, sabina-talipova commented
Open new PR https://github.com/silverstripe/silverstripe-admin/pull/1530

2023-06-21 04:35 UTC, closed without merging