ENH hide permission fields we arent using
silverstripe/silverstripe-admin pull request #1531
Opened 2023-06-23 04:45 UTC by andrewandante

2023-07-04 23:46 UTC, GuySartorelli requested changes
I'm a little iffy on this change, because entwine functions can be called from custom code. I doubt anyone is using these - but just in case, could you please keep the `showList` and `hideList` functions and just have them call the new show and hide functions?
i.e. something like
```js
showList: function (instant) {
  this.showGroupsList(instant);
  this.showMembersList(instant);
}
```

2023-07-05 04:20 UTC, andrewandante commented
I've rebased after the latest changes and restored the `showList` and `hideList` methods - though I kept the newer methods inside the `onMatch` and `onChange` because I now want them to do _slightly different_ things i.e. show one + hide one.

The OG methods will now show/hide _both_ the Member field and the Group field.

2023-07-05 21:58 UTC, GuySartorelli requested changes
Works well locally - just needs to be a little DRYer

2023-07-05 21:58 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.EditForm.js
> +    },
This is effectively the exact same code twice - can you please create a new function (maybe "toggleListDisplay" or similar) that takes a value as an argument, and sets the display accordingly?
For `onChange` the value is obviously `e.target.value`. For `onmatch` the value I think is just whichever of the two options `is(':checked')`

2023-07-05 21:58 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.EditForm.js
>        }
Given that this is all duplicated from `hideMembersList()`, can you please migrate that shared functionality into a shared function, so we can have DRY code?
Same with the `showGroupsList()` and `showMembersList()` shared functionality.

2023-07-06 21:37 UTC, GuySartorelli approved these changes
LGTM

2023-07-06 22:08 UTC, merged