MNT Add behat test for form validation
silverstripe/silverstripe-admin pull request #1543
Opened 2023-08-08 01:06 UTC by GuySartorelli

Requires https://github.com/silverstripe/silverstripe-framework/pull/10907 and https://github.com/silverstripe/silverstripe-frameworktest/pull/146 to be merged in before it will go green

## Issue
- https://github.com/silverstripe/silverstripe-admin/issues/1539

2023-08-09 00:50 UTC, sabina-talipova requested changes

2023-08-09 00:50 UTC, sabina-talipova commented on tests/behat/features/validation.feature
Could we check another fields, not just Email.

2023-08-09 00:51 UTC, GuySartorelli commented on tests/behat/features/validation.feature
We can, but can you please explain why? We're not testing if all form fields have implemented good validation logic - we're just testing if this new validator type correctly validates all fields in the form. The type of the field isn't really relevant.

2023-08-09 21:53 UTC, sabina-talipova approved these changes

2023-08-10 00:06 UTC, sabina-talipova commented
Guy, could you, please, check this issue.
https://github.com/silverstripe/silverstripe-admin/actions/runs/5791549093/job/15765872738?pr=1543#step:12:1014

2023-08-10 00:28 UTC, merged