FIX TinyMCE source view editor size
silverstripe/silverstripe-admin pull request #1561
Opened 2023-08-28 05:29 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1560

Regression isn't present in 2.0, so targeting 2

2023-08-28 05:38 UTC, emteknetnz commented
@dependabot rebase

2023-08-28 06:24 UTC, GuySartorelli requested changes

2023-08-28 06:24 UTC, GuySartorelli commented on client/src/styles/legacy/_tinymce.scss
I think this should probably be added to the silverstripe skin instead.

If this was caused by an update to tinymce, it'll be worth double checking the changelog to see if there's something specific they expected us to change.

It may be that simply rebuilding the skin the with latest tinymce version will resolve it without any customisation.

2023-08-28 06:52 UTC, emteknetnz commented on client/src/styles/legacy/_tinymce.scss
What's a silverstripe skin?

2023-08-28 07:22 UTC, GuySartorelli commented on client/src/styles/legacy/_tinymce.scss
https://github.com/silverstripe/silverstripe-admin/blob/2/client/src/tinymce/skins/ui/silverstripe/src/README.md

2023-08-29 05:39 UTC, emteknetnz commented
Closed in favor of https://github.com/silverstripe/silverstripe-admin/pull/1566

2023-08-29 05:39 UTC, closed without merging