MNT Replace sass-lint with stylelint
silverstripe/silverstripe-admin pull request #1727
Opened 2024-04-19 01:09 UTC by sabina-talipova

## Description

## Manual testing steps

## Issues

- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-04-23 02:06 UTC, GuySartorelli requested changes

2024-04-23 02:06 UTC, ChloeSartorelli commented on .stylelintrc.yml
1. Move this all into a new repo (like https://github.com/silverstripe/eslint-config/)
2. Make sure all modules can share the same stylelint rules by referencing the new repo

2024-04-23 02:06 UTC, ChloeSartorelli commented on .stylelintrc.yml
This will require updating all of the PRs so I won't continue reviewing until you've either responded or made that change.

2024-04-23 05:03 UTC, sabina-talipova commented on .stylelintrc.yml
Done. Moved configuration to the `silverstripe/eslint-config` module.

2024-04-25 22:00 UTC, GuySartorelli approved these changes
LGTM

2024-04-25 22:00 UTC, merged