FIX Use correct argument for FormBuilder context
silverstripe/silverstripe-admin pull request #1786
Opened 2024-06-18 04:31 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1778

2024-06-19 00:45 UTC, GuySartorelli requested changes

2024-06-19 00:45 UTC, GuySartorelli commented on client/src/components/SearchableDropdownField/SearchableDropdownField.js
> +    onChange(val, { value: val });
This change has resulted in a regression of https://github.com/silverstripe/silverstripe-admin/issues/1733
Probably still needs to be `val.value`, at least for single fields. Please read the comments in the issue and the PR 'cause I recall there was discussion about the difference between single and multi fields, as well.

2024-06-20 03:40 UTC, GuySartorelli commented
I can't de-select a record from the single `SearchableDropdownField` in an elemental block anymore.
I can select a _new_ record, but not deselect one that was already saved into the field.

2024-06-20 05:19 UTC, emteknetnz commented
I think this might just a be bad default when lazy-loading

Things are 'clearable' by when not lazy-loading because there's a default blank option that's selectable. This is not there when you lazy-load. However when I set `->setIsClearable(true)` alongside `->setIsLazyLoaded(true)` then I can clear the value.  

I think the solution here is that we just update the field to be clearable by default? This won't be a breaking change, just a behavioural change we could ship in 5.3

2024-06-20 05:31 UTC, emteknetnz commented
New issue to ensure field is always clearable https://github.com/silverstripe/silverstripe-admin/issues/1791

2024-06-21 03:03 UTC, GuySartorelli approved these changes
LGTM

2024-06-21 03:03 UTC, merged