Pull/edit link tinymce
silverstripe/silverstripe-admin pull request #1814
Opened 2024-08-20 05:57 UTC by satrun77

## Description

## Manual testing steps

## Issues

- https://github.com/silverstripe/silverstripe-cms/issues/2439

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-08-21 03:32 UTC, GuySartorelli requested changes
The comments in https://github.com/silverstripe/silverstripe-cms/pull/2993#pullrequestreview-2249599581 apply to this PR as well.

2024-08-21 05:19 UTC, satrun77 commented
I have updated the fix by moving the selection to the link element. This does not need the other PR. I have tested this with internal and external linking, it worked for me as expected.

2024-08-25 22:26 UTC, GuySartorelli requested changes
Thanks, this works great locally. Just one tiny change to make.

2024-08-25 22:26 UTC, ChloeSartorelli commented on client/src/legacy/TinyMCE_sslink.js
> +      // Find "a" node, issue https://github.com/silverstripe/silverstripe-cms/issues/2439
```suggestion
      // Find "a" node (we might have clicked on a child element e.g. "span")
```
There's no need to list the issue - git blame will inevitably lead us back to this PR and then to that issue if we really need that level of context on this.

2024-08-25 23:08 UTC, satrun77 commented on client/src/legacy/TinyMCE_sslink.js
> +      // Find "a" node, issue https://github.com/silverstripe/silverstripe-cms/issues/2439
Done updated

2024-08-25 23:26 UTC, GuySartorelli approved these changes
LGTM, works well locally. Thanks for this!

2024-08-25 23:26 UTC, merged