MNT Remove unused JS and CSS
silverstripe/silverstripe-admin pull request #1818
Opened 2024-08-28 22:27 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1378

2024-08-29 05:25 UTC, GuySartorelli requested changes

2024-08-29 05:25 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.Menu.js
There's still a reference that
> The (optional) second level is collapsible, hiding its children.

There's also still a lot of references like `li.children.opened`, `this.hasClass('collapsed')`, `<span class="toggle-children">` etc, a `toggle` function, `open` function, and `close` function...  that all look like they're related to this legacy feature.

2024-08-29 05:25 UTC, GuySartorelli commented on client/src/components/Menu/Menu.scss
There's still stuff like `.toggle-children` that look like they're related to this legacy feature.

2024-08-30 07:10 UTC, emteknetnz commented on client/src/legacy/LeftAndMain.Menu.js
Updated

2024-08-30 07:11 UTC, emteknetnz commented on client/src/components/Menu/Menu.scss
Updated

2024-09-02 02:35 UTC, GuySartorelli approved these changes
LGTM, works as expected.

2024-09-02 02:35 UTC, merged