NEW Give feedback of password strength
silverstripe/silverstripe-admin pull request #1832
Opened 2024-10-03 23:52 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/11413

2024-10-04 00:17 UTC, GuySartorelli commented
You might want to add a bit of a description about what you're actually doing here

2024-10-04 01:13 UTC, emteknetnz commented
Updated description, this PR is just a POC

2025-06-22 21:55 UTC, GuySartorelli commented
Note that this is no longer just a POC, despite all the descriptions saying it is. See https://github.com/silverstripe/silverstripe-framework/issues/11475.
I'll update the PR description as well.

2025-06-23 03:43 UTC, GuySartorelli requested changes
When typing, it's a bit jarring that the message can skip over strength types, which is a result of the debounce (e.g. I might see it go from "low" straight to "very strong" - I keep typing waiting for it to tell my my password is stronger, and get surprised that it isn't strong enough yet.... until I stop typing)

Can we add some indicator that it's updating while typing (e.g. a spinner)? Might be something to quickly buzz past the UX team?

Note that any JS changes here should also be reflected in login-forms

2025-06-23 03:43 UTC, ChloeSartorelli commented on client/src/legacy/ConfirmedPasswordField.js
> +document.addEventListener('input', (event) => {
Is there a reason we're using raw JS instead of jQuery or entwine?
I'm not bothered just wondering since it's not the style our JS tends to use.

2025-06-23 03:43 UTC, ChloeSartorelli commented on client/src/legacy/ConfirmedPasswordField.js
> +  const json = await response.json();
If there's an error (either non-200 response or unexpected body), we should clear any existing message in `strengthEl`

2025-06-23 06:58 UTC, emteknetnz commented on client/src/legacy/ConfirmedPasswordField.js
> +document.addEventListener('input', (event) => {
So that it also works on silverstripe/login-forms (without needing to add jquery to package.json)

2025-06-23 07:31 UTC, emteknetnz commented
Looks like I didn't have the debounce configured correctly which is why it was so jarring. I've added additional config `'maxWait': 300,` as well as just changing the debounce from 500 to 300.

300 seems to be a common value online for debounce it's related to human reaction time.  There will be a server lag which will increase this time, though I tried throttling the response in the network panel to GPRS, which kind of simulates a slow server, and the experience actually still seemed perfectly fine.  I don't think we need a loading indicator in its current state (which would probably increase complexity quite a lot)

2025-06-23 07:33 UTC, emteknetnz commented on client/src/legacy/ConfirmedPasswordField.js
> +  const json = await response.json();
Done

2025-06-24 01:24 UTC, ChloeSartorelli commented on client/src/legacy/ConfirmedPasswordField.js
> +document.addEventListener('input', (event) => {
This isn't the login-forms module, though?
It's probably fine, it's just a bit weird.

2025-06-25 00:25 UTC, GuySartorelli approved these changes
LGTM, will merge after the framework PR

2025-06-25 00:53 UTC, merged