Change button state before event process
silverstripe/silverstripe-admin pull request #1866
Opened 2024-12-03 04:16 UTC by hitaishi19

## Description

## Manual testing steps

## Issues
https://github.com/silverstripe/silverstripe-admin/issues/1865
- #

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-12-06 00:27 UTC, GuySartorelli requested changes
I've added the pull request template back into the PR description. Can you please fill it in, including ticking all of the checkboxes that apply? This will help you identify things that need to be done before this is ready to be reviewed (for example [build the dist javascript](https://docs.silverstripe.org/en/contributing/build_tooling/)).

Please also retarget this PR to the `2.3` branch so that it can be included as a patch release rather than waiting for the next minor release.
You may need to [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f) after retargetting the PR.


I have also tested this locally and found two problems:
1. Instead of swapping to the "loading" appearance, but button goes completely blank:
    ![image](https://github.com/user-attachments/assets/ed73e513-52a6-4455-b926-8c24f05dab51)
    It only uses the full loading styling after the `beforesubmitform` stuff has finished.
    An easy way to test this is to add a `sleep(5)` into the `validate()` method of an elemental block, then make sure to edit the block before hitting save.
1. If an elemental block has a validation error, the button stays disabled forever.

2024-12-06 00:31 UTC, GuySartorelli commented
To fix 1, probably you need to move everything in the `if($(button).is('button')) {` conditional block.

To fix 2, I suspect the `clearButton()` function needs to be called in the `if (invalid) {` conditional block.

2024-12-09 02:36 UTC, GuySartorelli requested changes

2024-12-09 02:36 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.js
>          if($(button).is('button')) {
This condition and the code in this block is now duplicated - does it _need_ to be in both places, or can this second block be removed?

If it does need to be in both places separately, please abstract it to a function call, and add some in-line code comments explaining _why_ it needs to happen both here _and_ above.

2024-12-09 02:39 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.js
> +      $(button).prop('disabled', true);
This used to happen before the conditional block. That should probably remain the case.

2024-12-09 02:39 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.js
> +      if ($(button).is("button")) {
```suggestion
      if ($(button).is('button')) {
```

2024-12-09 02:39 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.js
> +        $(button).css($(button).outerWidth() + "px");
```suggestion
        $(button).css($(button).outerWidth() + 'px');
```

2024-12-09 02:45 UTC, GuySartorelli commented
Problem 2 from https://github.com/silverstripe/silverstripe-admin/pull/1866#pullrequestreview-2483336309 is still happening. Did you test that scenario?

2024-12-09 03:34 UTC, hitaishi19 commented
> Problem 2 from [#1866 (review)](https://github.com/silverstripe/silverstripe-admin/pull/1866#pullrequestreview-2483336309) is still happening. Did you test that scenario?

This is not reproducing to me, can you please share the reproduction steps?

2024-12-09 03:39 UTC, GuySartorelli commented
1. Create a block
1. Add some validation to an elemental block which will fail
    ```php
    public function validate()
    {
        $result = parent::validate();
        $result->addFieldError('Title', 'FAILURE');
        return $result;
    }
    ```
1. Make a change to the block (or else validation won't trigger)
1. Click "save" on the page.

2024-12-09 03:40 UTC, GuySartorelli commented on client/src/legacy/LeftAndMain.js
> +              "</div>"
```suggestion
              '</div>'
```
Sorry, didn't notice this one before

2024-12-09 21:36 UTC, GuySartorelli approved these changes
LGTM, works well locally. Thanks for taking the time to implement this fix.

2024-12-09 21:36 UTC, merged